application:
  port: 8000
  hmac_secret: "my-super-secret"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  timeout_milliseconds: 10000
